apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    app.kubernetes.io/part-of: kac
    kac.team: payments
---
apiVersion: v1
kind: Namespace
metadata:
  name: pe
  labels:
    app.kubernetes.io/part-of: kac
    kac.team: pe
